const morpheusToSwagger = input => {
  const { models, routes } = input;

  const successResponse = route => ({
    '200': {
      description: `a ${route.returns.name}`,
      schema: {
        $ref: `#/definitions/${route.returns.name}`
      }
    }
  });

  const objectify = arr => arr.reduce((arr, a) => Object.assign(arr, a));

  const toSwaggerType = tpe => {
    // refer to
    // https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
    const scalaToSwagger = {
      String: {
        type: 'string'
      },
      Int: {
        type: 'integer',
        format: 'int32'
      },
      Long: {
        type: 'integer',
        format: 'int64'
      },
      Float: {
        type: 'number',
        format: 'float'
      },
      Double: {
        type: 'number',
        format: 'double'
      },
      Date: {
        type: 'string',
        format: 'date'
      },
      DateTime: {
        type: 'string',
        format: 'date-time'
      },
      Boolean: {
        type: 'boolean'
      }
    };

    if (models[tpe]) {
      return {
        schema: {
          $ref: `#/definitions/${tpe}`
        }
      }
    } else {
       return scalaToSwagger[tpe] || { type: tpe };
    }
  }

  const getRouteParamName = ({ name = 'unknown' }) => name;

  const getRoutePath = ({ route }) => route.reduce((path, part) => {
    if (part.str) return `${path}/${part.str}`;
    if (part.routeParam) return `${path}/{${getRouteParamName(part.routeParam)}}`;
    return path;
  }, '');

  const getRouteParameters = (route) => {
    const pathParams = route.route
      .filter(part => Object.keys(part).indexOf('routeParam') !== -1)
      .map(({ routeParam }) => Object.assign({
        in: 'path',
        name: getRouteParamName(routeParam),
        required: routeParam.required,
      }, toSwaggerType(routeParam.tpe.name)));

    const { params = [], body } = route;
    const queryParams = params.map(param => Object.assign({
      in: 'query',
      name: param.name,
      required: param.required
    }, toSwaggerType(param.tpe.name)));

    const bodyParams = body ? [{
      in: 'body',
      name: 'body',
      required: true,
      schema: {
        $ref: `#/definitions/${body.tpe.name}`
      }
    }] : [];

    return [...pathParams, ...queryParams, ...bodyParams];
  };


  const paths = routes.map(route => {
    const path = getRoutePath(route);
    const parameters = getRouteParameters(route);

    return {
      [path]: {
        [route.method]: {
          summary: route.desc,
          consumes: [
            'application/json'
          ],
          produces: [
            'application/json'
          ],
          parameters,
          responses: successResponse(route)
        }
      }
    }
  });

  const definitions = models.map(model => ({
    [model.name]: {
      type: 'object',
      properties: objectify(model.members.map(member => ({
        [member.name]: Object.assign({
          description: member.desc
        }, toSwaggerType(member.tpe.name))
      })))
    }
  }));

  const swaggerSpec = {
    swagger: '2.0',
    info: {
      description: 'Autogenerated swagger spec',
      version: '0.1.0',
      title: 'metarpheus-swagger',
    },
    paths: objectify(paths),
    definitions: objectify(definitions)
  };

  return swaggerSpec;

};

module.exports = morpheusToSwagger;
